### ISSUE TITLE
cmd process must be use admin

### ISSUE THREAD

**Issue by teynakopha** [ronjunelopez/ExampleWifi#1]
thank you for class hotspot wifi 
i have use class hotspot wifi from you and can't excecute cmd because user is not administrator 
![image](https://cloud.githubusercontent.com/assets/13892479/26665069/33323d6c-46c1-11e7-84e5-9a4fd246bb1d.png)

**Comment by ronjunevaldoz** [comment]
You should run the cmd using Administrator Privilege.

Option 1:

-> start menu
-> search -> cmd
-> cmd -> right click -> then run as Administrator


Option 2:

-> start menu
-> search -> visual studio
-> visual studio -> right click -> then run as Administrator
